var voxelTypes_Translate = {
    "A": "字母-A[发光]",
    "B": "字母-B[发光]",
    "C": "字母-C[发光]",
    "D": "字母-D[发光]",
    "E": "字母-E[发光]",
    "F": "字母-F[发光]",
    "G": "字母-G[发光]",
    "H": "字母-H[发光]",
    "I": "字母-I[发光]",
    "J": "字母-J[发光]",
    "K": "字母-K[发光]",
    "L": "字母-L[发光]",
    "M": "字母-M[发光]",
    "N": "字母-N[发光]",
    "O": "字母-O[发光]",
    "P": "字母-P[发光]",
    "Q": "字母-Q[发光]",
    "R": "字母-R[发光]",
    "S": "字母-S[发光]",
    "T": "字母-T[发光]",
    "U": "字母-U[发光]",
    "V": "字母-V[发光]",
    "W": "字母-W[发光]",
    "X": "字母-X[发光]",
    "Y": "字母-Y[发光]",
    "Z": "字母-Z[发光]",
    "acacia": "自然-金合欢木",
    "add": "符号-+[发光]",
    "air": "自然-空气[气体]",
    "air_duct": "建筑-通风管",
    "ampersand": "符号-&[发光]",
    "asterisk": "符号-*[发光]",
    "at": "符号-@[发光]",
    "backslash": "符号-\\[发光]",
    "bamboo": "自然-竹子",
    "barrier": "自然-空气墙",
    "bat_window": "建筑-蝙蝠窗户",
    "bear_footprint": "自然-熊脚印",
    "biscuit": "食物-饼干",
    "black": "颜色-<span style=\"background-color: #000000\">黑色</span>",
    "black_glass": "建筑-黑色玻璃",
    "blue": "颜色-<span style=\"background-color: #0000ff\">蓝色</span>",
    "blue_decorative_light": "建筑-蓝色彩灯[发光][动态]",
    "blue_gift": "建筑-蓝色礼物盒",
    "blue_glass": "建筑-蓝色玻璃",
    "blue_grass": "地形-蓝色草地",
    "blue_grass_all": "地形-蓝色草",
    "blue_light": "光源-蓝色灯[发光]",
    "blue_surface_01": "自然-蓝色地表-1",
    "blue_surface_02": "自然-蓝色地表-2",
    "blueberry_juice": "食物-蓝莓汁",
    "board0": "建筑-空白棋盘方块",
    "board1": "建筑-棋盘方块┼",
    "board10": "建筑-棋盘方块╬",
    "board11": "建筑-棋盘方块╣│",
    "board12": "建筑-棋盘方块╗",
    "board13": "建筑-棋盘方块┫│",
    "board14": "建筑-棋盘方块║",
    "board15": "建筑-棋盘方块┘│═",
    "board2": "建筑-棋盘方块·┼",
    "board3": "建筑-棋盘方块╗",
    "board4": "建筑-棋盘方块┫",
    "board5": "建筑-棋盘方块╳┼",
    "board6": "建筑-棋盘方块╲┼",
    "board7": "建筑-棋盘方块╱╗",
    "board8": "建筑-棋盘方块╲┫║",
    "board9": "建筑-棋盘方块╱┫║",
    "board_01": "建筑-棕色木板",
    "board_02": "建筑-褐色木板",
    "board_03": "建筑-黄色十字木板",
    "board_04": "建筑-黄色条纹木板",
    "board_05": "建筑-褐色条纹木板",
    "board_06": "建筑-棕色条纹木板",
    "board_07": "建筑-浅棕色木板",
    "bookshelf": "建筑-书架",
    "bounce_pad": "建筑-蹦床",
    "bracket_close": "符号-][发光]",
    "bracket_open": "符号-[[发光]",
    "brick_01": "建筑-黄色砖",
    "brick_02": "建筑-蓝色砖",
    "brick_red": "颜色-<span style=\"background-color: #de4a4a\">砖红色</span>",
    "button": "建筑-按钮",
    "cadet_blue": "颜色-<span style=\"background-color: #37629c\">学员蓝</span>",
    "candy": "食物-糖果",
    "caret": "符号-^[发光]",
    "carpet_01": "建筑-黄色地毯",
    "carpet_02": "建筑-蓝色地毯",
    "carpet_03": "建筑-粉色地毯",
    "carpet_04": "建筑-绿色地毯",
    "carpet_05": "建筑-红色花形地毯",
    "carpet_06": "建筑-灰色地毯",
    "carpet_07": "建筑-红色格子地毯",
    "carpet_08": "建筑-黑白格子地毯",
    "carpet_09": "建筑-蓝白格子地毯",
    "carpet_10": "建筑-绿白格子地毯",
    "carpet_11": "建筑-黄白格子地毯",
    "carpet_12": "建筑-粉白格子地毯",
    "carpet_13": "建筑-红白格子地毯",
    "coffee": "食物-咖啡[液体]",
    "coffee_gray": "颜色-<span style=\"background-color: #795548\">咖啡灰色</span>",
    "colon": "符号-:[发光]",
    "color_glass": "建筑-花色玻璃",
    "comma": "符号-,[发光]",
    "conveyor": "建筑-传送带[动态]",
    "crane_lantern": "建筑-吊灯/鹤灯[发光]",
    "crane_roof_01": "建筑-吊顶/鹤顶-1",
    "crane_roof_02": "建筑-吊顶/鹤顶-2",
    "cross_window": "建筑-交叉花纹窗户",
    "dark_blue_grass": "地形-深蓝色草地",
    "dark_blue_grass_all": "地形-深蓝色草",
    "dark_brick_00": "建筑-深色砖块",
    "dark_brick_01": "建筑-深色小砖块-1",
    "dark_brick_02": "建筑-深色小砖块-2",
    "dark_grass": "自然-深色草地",
    "dark_grass_all": "地形-深色草",
    "dark_grass_rock": "地形-岩石上的深色草",
    "dark_grass_sand": "地形-砂岩上的深色草",
    "dark_gray": "颜色-<span style=\"background-color: #424242\">深灰色</span>",
    "dark_orchid": "颜色-<span style=\"background-color: #7b1fa2\">暗兰紫</span>",
    "dark_purple_grass": "地形-深紫色草地",
    "dark_purple_grass_all": "地形-深紫色草",
    "dark_red": "颜色-<span style=\"background-color: #9e1906\">暗兰紫</span>",
    "dark_red_grass": "地形-深红色草地",
    "dark_red_grass_all": "地形-深红色草",
    "dark_salmon": "颜色-<span style=\"background-color: #dba463\">暗鲑红</span>",
    "dark_sand": "地形-深色沙子",
    "dark_slate_blue": "颜色-<span style=\"background-color: #283573\">深蓝色</span>",
    "dark_stone": "自然-深色石头",
    "dark_surface": "自然-紫色地表",
    "dark_volcanic_rock": "地形-深色火山岩",
    "dark_yellow_grass": "地形-深黄色草地",
    "dark_yellow_grass_all": "地形-深黄色草",
    "dirt": "自然-泥土",
    "divide": "符号-÷[发光]",
    "dollar": "符号-$[发光]",
    "eight": "数字-8[发光]",
    "equal": "符号-=[发光]",
    "exclamation_mark": "符号-![发光]",
    "express_box": "建筑-快递箱",
    "fan": "建筑-风扇",
    "firecracker": "建筑-爆竹",
    "five": "数字-5[发光]",
    "four": "数字-4[发光]",
    "fu": "建筑-福",
    "geometric_window_01": "建筑-方框窗户-1",
    "geometric_window_02": "建筑-方框窗户-2",
    "glass": "建筑-玻璃",
    "gold_trim_brick": "建筑-镶金砖",
    "grape_juice": "食物-葡萄汁[液体]",
    "grass": "自然-草地",
    "grass_all": "地形-草",
    "grass_rock": "地形-岩石上的草",
    "grass_sand": "地形-砂岩上的草",
    "greater_than": "符号->[发光]",
    "green_decorative_light": "建筑-绿色彩灯[发光][动态]",
    "green_glass": "建筑-绿色玻璃",
    "green_leaf": "自然-绿色树叶",
    "green_light": "光源-绿色灯[发光]",
    "greenbelt_L": "建筑-绿化带-1",
    "greenbelt_L1": "建筑-绿化带-2",
    "grey_stone_brick": "建筑-灰色石砖",
    "honeycomb_01": "自然-蜂巢方块-1",
    "honeycomb_02": "自然-蜂巢方块-2",
    "ice": "自然-冰",
    "ice_brick": "建筑-冰砖",
    "ice_wall": "建筑-冰墙",
    "indigo_light": "光源-青色灯[发光]",
    "lab_lamp_01": "建筑-实验室灯[发光]",
    "lab_lamp_02": "建筑-实验室四格灯[发光]",
    "lab_lamp_03": "建筑-实验室黄色灯[发光]",
    "lab_material_01": "建筑-实验室方块-1",
    "lab_material_02": "建筑-实验室方块-2",
    "lab_material_03": "建筑-实验室方块-3",
    "lab_material_04": "建筑-实验室方块-4",
    "lab_material_05": "建筑-实验室方块-5[发光]",
    "lab_material_06": "建筑-实验室方块-6",
    "lab_material_07": "建筑-实验室方块-7",
    "lab_material_08": "建筑-实验室方块-8",
    "lab_material_09": "建筑-实验室方块-9",
    "lab_material_10": "建筑-实验室方块-10",
    "lab_material_11": "建筑-实验室方块-11",
    "lab_material_12": "建筑-实验室方块-12",
    "lab_material_13": "建筑-实验室方块-13",
    "lab_material_14": "建筑-实验室方块-14",
    "lab_material_15": "建筑-实验室方块-15",
    "lab_screen": "建筑-实验室屏幕",
    "lab_wire": "建筑-实验室电缆",
    "lantern_01": "建筑-黄色灯",
    "lantern_02": "建筑-白色灯",
    "lava01": "自然-深红色熔岩方块",
    "lava02": "自然-橙色熔岩方块",
    "leaf_01": "自然-青色树叶",
    "leaf_02": "自然-红色树叶",
    "leaf_03": "自然-橙色树叶",
    "leaf_04": "自然-粉色树叶",
    "leaf_05": "自然-深绿色树叶",
    "leaf_06": "自然-金色树叶",
    "ledfloor01": "建筑-蓝色LED地板[发光][动态]",
    "ledfloor02": "建筑-紫色LED地板[发光][动态]",
    "lemon": "颜色-<span style=\"background-color: #fff74c\">柠檬黄</span>",
    "lemon_juice": "食物-柠檬汁[液体]",
    "less_than": "符号-<[发光]",
    "light_blue_grass": "地形-亮蓝色草地",
    "light_blue_grass_all": "地形-亮蓝色草",
    "light_dirt": "地形-亮色泥土",
    "light_gray": "颜色-<span style=\"background-color: #aeaeae\">浅灰色</span>",
    "light_grey_stone_brick": "建筑-浅灰色石砖",
    "light_purple_grass_": "地形-亮紫色草地",
    "light_purple_grass_all": "亮紫色草",
    "light_sand": "地形-亮色沙子",
    "light_volcanic_rock": "地形-亮色火山岩",
    "lime_juice": "食物-柠檬汁[液体]",
    "macaroon": "食物-马卡龙",
    "maroon": "颜色-<span style=\"background-color: #833100\">栗色</span>",
    "medium_gray": "颜色-<span style=\"background-color: #717171\">中灰色</span>",
    "medium_green": "颜色-<span style=\"background-color: #0a7f07\">中绿色</span>",
    "medium_orchid": "颜色-<span style=\"background-color: #ba68c8\">中兰紫</span>",
    "medium_purple": "颜色-<span style=\"background-color: #8b8cde\">中紫色</span>",
    "medium_spring_green": "颜色-<span style=\"background-color: #37ffc1\">中春绿</span>",
    "medium_violet_red": "颜色-<span style=\"background-color: #dd348d\">中紫红</span>",
    "medium_yellow": "颜色-<span style=\"background-color: #ffd541\">中黄色</span>",
    "milk": "食物-牛奶[液体]",
    "mint_green": "颜色-<span style=\"background-color: #ffd541\">薄荷绿</span>",
    "mint_green_light": "光源-薄荷绿灯[发光]",
    "multiply": "符号-×[发光]",
    "navajo_white": "颜色-<span style=\"background-color: #fbdf9b\">纳瓦霍白</span>",
    "nine": "数字-9[发光]",
    "olive_green": "颜色-<span style=\"background-color: #758f38\">橄榄绿</span>",
    "one": "数字-1[发光]",
    "orange": "颜色-<span style=\"background-color: #ff940e\">橙色</span>",
    "orange_grass": "地形-橙色草地",
    "orange_grass_all": "地形-橙色草",
    "orange_juice": "食物-橙汁[液体]",
    "orange_light": "光源-橙色灯[发光]",
    "orange_red": "颜色-<span style=\"background-color: #e65100\">橙红色</span>",
    "palace_carving": "建筑-宫殿雕刻",
    "palace_cloud": "建筑-宫殿祥云图案",
    "palace_eaves_01": "建筑-宫殿屋檐-1",
    "palace_eaves_02": "建筑-宫殿屋檐-2",
    "palace_eaves_03": "建筑-宫殿屋檐-3",
    "palace_eaves_04": "建筑-宫殿屋檐-4",
    "palace_eaves_05": "建筑-宫殿屋檐-5",
    "palace_eaves_06": "建筑-宫殿屋檐-6",
    "palace_eaves_07": "建筑-宫殿屋檐-7",
    "palace_eaves_08": "建筑-宫殿屋檐-8",
    "palace_floor": "建筑-宫殿地板",
    "palace_lamp": "建筑-宫殿灯[光源]",
    "palace_roof": "建筑-宫殿屋顶",
    "palace_window": "建筑-宫殿窗户",
    "pale_green": "颜色-<span style=\"background-color: #d2e089\">浅绿色</span>",
    "palm": "自然-棕榈树",
    "paren_close": "符号-)[发光]",
    "paren_open": "符号-([发光]",
    "peach_juice": "食物-桃汁[液体]",
    "percent": "符号-%[发光]",
    "period": "符号-.[发光]",
    "peru": "颜色-<span style=\"background-color: #bb7547\">秘鲁色</span>",
    "pink": "颜色-<span style=\"background-color: #ff7d9c\">粉色</span>",
    "pink_cake": "食物-粉色蛋糕",
    "pink_grass": "地形-粉色草地",
    "pink_grass_all": "地形-粉色草",
    "pink_light": "光源-粉色灯[光源]",
    "plank_01": "建筑-条纹木板-1",
    "plank_02": "建筑-条纹木板-2",
    "plank_03": "建筑-条纹木板-3",
    "plank_04": "建筑-条纹木板-4",
    "plank_05": "建筑-黄色斜条纹木板",
    "plank_06": "建筑-棕色斜条纹木板",
    "plank_07": "建筑-褐色斜条纹木板",
    "polar_ice": "自然-极地冰",
    "polar_region": "自然-极地地表",
    "pound": "符号-#[发光]",
    "powder_blue": "颜色-<span style=\"background-color: #c1ecf8\">粉蓝色</span>",
    "pumpkin": "自然-南瓜",
    "pumpkin_lantern": "建筑-南瓜灯",
    "purple": "光源-紫色灯",
    "purple_grass": "地形-紫色草地",
    "purple_grass_all": "地形-紫色草",
    "purple_surface_01": "自然-紫色地表-1",
    "purple_surface_02": "自然-紫色地表-2",
    "quartz_brick": "建筑-石英砖",
    "question_mark": "符号-?[发光]",
    "quotation_mark": "符号-\"[发光]",
    "rainbow_cube": "建筑-彩虹方块[动态]",
    "red": "颜色-<span style=\"background-color: #f50e0e\">红色</span>",
    "red_brick": "建筑-红砖",
    "red_brick_floor": "建筑-红砖地板",
    "red_brick_wall": "建筑-红砖墙",
    "red_decorative_light": "建筑-红色彩灯[发光][动态]",
    "red_gift": "建筑-红色礼物盒",
    "red_glass": "建筑-红色玻璃",
    "red_light": "光源-红色灯[发光]",
    "rock": "自然-岩石",
    "roof_blue_04": "建筑-蓝色瓦片屋顶",
    "roof_green": "建筑-绿色瓦片屋顶",
    "roof_grey": "建筑-灰色瓦片屋顶",
    "roof_purple": "建筑-紫色瓦片屋顶",
    "roof_red": "建筑-红色瓦片屋顶",
    "roof_yellow": "建筑-黄色瓦片屋顶",
    "sakura_pink": "颜色-<span style=\"background-color: #ffbfe2\">樱花粉</span>",
    "sand": "自然-沙子",
    "sand_stones": "地形-砂岩",
    "semicolon": "符号-;[发光]",
    "seven": "数字-7[发光]",
    "sienna": "颜色-<span style=\"background-color: #846b29\">赭色</span>",
    "six": "数字-6[发光]",
    "sky_blue": "颜色-<span style=\"background-color: #58aae7\">天蓝色</span>",
    "slash": "符号-/[发光]",
    "snow": "自然-雪",
    "snow_grass": "地形-积雪的草地",
    "snow_land": "地形-积雪的地面",
    "snowflake_lamp": "建筑-雪花灯[发光][动态]",
    "snowland": "自然-积雪的地面",
    "snowman_body": "建筑-雪人的身体",
    "snowman_head": "建筑-雪人的头",
    "soy_sauce": "食物-酱油[液体]",
    "special_grass_01": "地形-紫色螺旋形草地",
    "special_grass_02": "地形-紫色螺旋形草",
    "special_grass_03": "地形-绿色螺旋形草地",
    "special_grass_04": "地形-绿色螺旋形草",
    "special_grass_05": "地形-蓝色螺旋形草地",
    "special_grass_06": "地形-蓝色螺旋形草",
    "special_grass_07": "地形-黄色螺旋形草地",
    "special_grass_08": "地形-黄色螺旋形草",
    "special_grass_09": "地形-特殊紫色草地",
    "special_grass_10": "地形-特殊浅紫色草地",
    "special_grass_11": "地形-黄绿色草地",
    "special_grass_12": "地形-黄绿色草",
    "special_grass_13": "地形-岩石上的黄绿色草",
    "special_grass_14": "地形-浅绿色草地",
    "special_grass_15": "地形-浅绿色草",
    "special_grass_16": "地形-岩石上的浅绿色草",
    "special_land_01": "地形-紫色地面",
    "special_sand_01": "地形-带蓝色海螺的沙子",
    "special_sand_02": "地形-带粉色贝壳的沙子",
    "special_sand_03": "地形-带黄色海星的沙子",
    "special_sand_04": "地形-干沙子",
    "special_sand_05": "地形-深色沙子",
    "spiderweb": "自然-蜘蛛网",
    "stained_glass": "建筑-彩色玻璃",
    "stainless_steel": "建筑-不锈钢",
    "star_lamp": "建筑-星星灯[发光][动态]",
    "stone": "自然-石头",
    "stone_brick_01": "建筑-小石砖-1",
    "stone_brick_02": "建筑-小石砖-2",
    "stone_pillar_03": "建筑-石柱-1",
    "stone_pillar_04": "建筑-石柱-2",
    "stone_pillar_05": "建筑-石柱-3",
    "stone_pillar_06": "建筑-石柱-4",
    "stone_wall": "建筑-石砖墙-1",
    "stone_wall_01": "建筑-石砖墙-2",
    "strawberry_juice": "食物-草莓汁[液体]",
    "stripe_01": "颜色-红白条纹方块",
    "stripe_02": "颜色-蓝白条纹方块",
    "stripe_03": "颜色-橙白条纹方块",
    "stripe_04": "颜色-绿白条纹方块",
    "stripe_05": "颜色-紫白条纹方块",
    "subtract": "符号--[发光]",
    "television": "建筑-电视",
    "three": "数字-3[发光]",
    "tilde": "符号-~[发光]",
    "toolbox": "建筑-工具箱",
    "traditional_window": "建筑-古代窗户",
    "treasure_chest": "建筑-藏宝箱",
    "turquoise": "颜色-<span style=\"background-color: #4dd0e1\">绿松色</span>",
    "two": "数字-2[发光]",
    "warm_yellow_light": "光源-暖黄色灯[发光]",
    "water": "自然-水[液体]",
    "white": "颜色-<span style=\"background-color: #ffffff\">白色</span>",
    "white_grass": "自然-白色草",
    "white_light": "光源-白色灯[发光]",
    "window": "建筑-窗户",
    "windygrass": "自然-风吹草动[动态]",
    "winter_leaf": "自然-冬天的树叶/积雪的树叶",
    "withered_grass": "地形-枯萎的草",
    "withered_grass_land": "地形-枯萎的草地",
    "wood": "自然-木头",
    "wooden_box": "建筑-木箱子",
    "woodstone_12": "建筑-嵌木的石砖",
    "yellow_decorative_light": "光源-暖黄色灯[发光]",
    "yellow_grass": "自然-黄色草",
    "yellow_green": "颜色-<span style=\"background-color: #58aae7\">天蓝色</span>",
    "yellow_light": "光源-黄色灯[发光]",
    "zero": "数字-0[发光]"
}