site_name: Box3 社区文档
repo_url: https://github.com/qndm/box3-docs
edit_uri: edit/main/docs/
repo_name: box3-docs
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.tabs
    - navigation.expand
    - content.tabs.link
    - search.suggest
    - search.highlight
  language: zh
  palette:
    - scheme: default
      primary: light blue
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: 亮色模式
    - scheme: slate
      primary: light blue
      toggle:
        icon: material/weather-night
        name: 暗色模式
  custom_dir: overrides
extra_css:
  - _assets/icons.css
  - _assets/global.css

extra_javascript:
  - _assets/iconsParser.js
  - _assets/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/gsap/3.11.3/gsap.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/gsap/3.11.3/ScrollToPlugin.min.js
  #- _assets/anchorParser.js
  - _assets/voxelsID.js
  - _assets/voxelsType.js
  - _assets/voxelIdsTable.js
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/icons
  - pymdownx.tilde
  - tables
plugins:
  - search:
      lang: en
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      width: "100%"
      height: auto
      zoomable: true
      draggable: true
      auto_caption: false
      caption_position: bottom
  - minify:
      minify_html: true
nav:
  - 主页:
    - 介绍:
      - 欢迎: index.md
      - 关于文档: about.md
      - 更新: changes.md
      - 计划: todo.md
  - 学习:
    - learn/index.md
    - 粒子特效:
      - learn/particle/index.md
    - JavaScript:
      - learn/js/index.md
      - 基础教程:
        - learn/js/base/index.md
        - 开始: 
          - Hello, World!: learn/js/base/01-hello-world.md
          - 欢迎玩家: learn/js/base/02-greeting.md
    - 大佬の宝典:
      - SQL快速入门: learn/community-articles/Nomen-sql.md
      - OOP（面向对象编程）快速入门: learn/community-articles/Nomen-oop.md
      - 如何优雅地写注释: learn/community-articles/Nomen-comment.md
      - 快速上手函数: learn/community-articles/Nomen-function.md
    - 算法:
      - BFS: learn/arithmetic/BFS.md
      - DFS: learn/arithmetic/DFS.md
  - 实例教程:
    - example/index.md
    - LightDotCutter 简单PVE游戏:
      - 起步: example/light-dot-cutter/01-start.md
      - 生成敌人: example/light-dot-cutter/02-setup-enemy.md
      #     - 实现玩家攻击: example/light-dot-cutter/03-attack.md
      #     - 添加敌人和玩家的血量: example/light-dot-cutter/04-health.md
      #     - 设置奖励: example/light-dot-cutter/05-reward.md
      #     - 添加特效: example/light-dot-cutter/06-effect.md
      #     - 重构和扩展: example/light-dot-cutter/07-extra.md
      #     - 优化: example/light-dot-cutter/08-optimization.md
  - API参考:
    - api/index.md
    - <icon name='namespace'>图标参考</icon>: api/icons.md
    - <def>world</def> & <def>Box3World</def> / <def>GameWorld</def> <span block>世界模块</span>: api/world.md
    - <def>voxels</def> & <def>Box3Voxels</def> / <def>GameVoxels</def> <span block>方块模块</span>: api/voxels.md
    - <def>db</def> & <def>Box3DataBase</def> <span block>数据库模块</span>: api/db.md
    - <def>storage</def> & <def>GameStorage</def> <span block>数据存储模块</span>: api/storage.md
    - <def>gui</def> & <def>GameGUI</def> <span block>用户图形界面模块</span>: api/gui.md
    - <def>rtc</def> & <def>GameRTC</def> <span block>实时语言通信模块</span>: api/rtc.md
    - <def>http</def> & <def>Box3HttpAPI</def> / <def>GameHttpAPI</def> <span block>HTTP模块</span>: api/http.md
    - <def>console</def> & <def>GameConsole</def> <span block>控制台</span>: api/console.md
    - <span block>杂项</span>: api/tool.md
    - <icon name='class'>类</icon>:
      - <def>Box3Entity</def> / <def>GameEntity</def> <span block> 实体</span>: api/class/Entity.md
      - <def>Box3Player</def> / <def>GamePlayer</def> <span block>玩家</span>: api/class/Player.md
      - <def>Box3Animation</def> / <def>GameAnimation</def> <span block>动画</span>: api/class/Animation.md
      - <def>Box3Zone</def> / <def>GameZone</def> <span block>区域</span>: api/class/Zone.md
      - <def>GameMotionController</def> <span block>动作控制器</span>: api/class/MotionController.md
      - <def>Box3QueryResult</def> <span block>数据查找结果</span>: api/class/QueryResult.md
      - <def>GameDataStorage</def> <span block>数据存储空间</span>: api/class/DataStorage.md
      - <def>QueryList</def> <span block>数据查询列表</span>: api/class/QueryList.md
      - <def>PlayerNavigator</def> <span block>用户设备相关</span>: api/class/PlayerNavigator.md
      - <def>GameRTCChannel</def> <span block>RTC通道</span>: api/class/RTCChannel.md
      - <def>Box3EventHandlerToken</def> / <def>GameEventHandlerToken</def> <span block>事件令牌</span>: api/class/EventHandlerToken.md
      - <def>Box3HttpFetchResponse</def> / <def>GameHttpFetchResponse</def> <span block>请求响应</span>: api/class/HttpFetchResponse.md
      - <def>Box3HttpRequest</def> / <def>GameHttpRequest</def> <span block>[无效]HTTP请求</span>: api/class/HttpRequest.md
      - <def>Box3HttpResponse</def> / <def>GameHttpResponse</def> <span block>[无效]HTTP响应</span>: api/class/HttpResponse.md
      - <def>Sound</def> <span block>声音</span>: api/class/Sound.md
    - <icon name='event'>事件</icon>:
      - <def>Box3TickEvent</def> / <def>GameTickEvent</def> <span block>时钟事件</span>: api/event/TickEvent.md
      - <def>Box3RespawnEvent</def> / <def>GameRespawnEvent</def> <span block>玩家重生事件</span>: api/event/RespawnEvent.md
      - <def>Box3DamageEvent</def> / <def>GameDamageEvent</def> <span block>实体伤害事件</span>: api/event/DamageEvent.md
      - <def>Box3DieEvent</def> / <def>GameDieEvent</def> <span block>实体死亡事件</span>: api/event/DieEvent.md
      - <def>Box3EntityEvent</def> / <def>GameEntityEvent</def> <span block>实体创建销毁事件</span>: api/event/EntityEvent.md
      - <def>Box3PlayerEntityEvent</def> / <def>GamePlayerEntityEvent</def> <span block>玩家实体创建销毁事件</span>: api/event/PlayerEntityEvent.md
      - <def>Box3ChatEvent</def> / <def>GameChatEvent</def> <span block>聊天事件</span>: api/event/ChatEvent.md
      - <def>Box3ClickEvent</def> / <def>GameClickEvent</def> <span block>点击事件</span>: api/event/ClickEvent.md
      - <def>Box3InputEvent</def> / <def>GameInputEvent</def> <span block>输入事件</span>: api/event/InputEvent.md
      - <def>GameKeyBoardEvent</def> <span block>键盘事件</span>: api/event/KeyBoardEvent.md
      - <def>Box3InteractEvent</def> / <def>GameInteractEvent</def> <span block>实体互动事件</span>: api/event/InteractEvent.md
      - <def>Box3EntityContactEvent</def> / <def>GameEntityContactEvent</def> <span block>实体碰撞事件</span>: api/event/EntityContactEvent.md
      - <def>Box3VoxelContactEvent</def> / <def>GameVoxelContactEvent</def> <span block>方块碰撞事件</span>: api/event/VoxelContactEvent.md
      - <def>Box3FluidContactEvent</def> / <def>GameFluidContactEvent</def> <span block>液体碰撞事件</span>: api/event/FluidContactEvent.md
      - <def>Box3TriggerEvent</def> / <def>GameTriggerEvent</def> <span block>触发器事件</span>: api/event/TriggerEvent.md
      - <def>Box3AnimationEvent</def> / <def>GameAnimationEvent</def> <span block>动画事件</span>: api/event/AnimationEvent.md
    - <icon name='type'>结构类型</icon>:
      - <icon name='namespace'>基本数据类型</icon>:
        - <def>string</def> & <def>String</def> <span block>字符串</span>: api/type/base/String.md
        - <def>number</def> & <def>Number</def> <span block>数字</span>: api/type/base/Number.md
        - <def>boolean</def> & <def>Boolean</def> <span block>布尔值</span>: api/type/base/Boolean.md
        - <def>any</def> <span block>任意类型</span>: api/type/base/any.md
        - <def>void</def> <span block>无类型</span>: api/type/base/void.md
        - <def>null</def> <span block>空值</span>: api/type/base/null.md
        - <def>undefined</def> <span block>未定义</span>: api/type/base/undefined.md
        - <def>Partial</def>: api/type/base/Partial.md
        - <def>URL</def> <span block>链接</span>: api/type/base/URL.md
      - <icon name='namespace'>Box3 基本数据类型</icon>:
        - <def>Box3Vector3</def> / <def>GameVector3</def> <span block>三维向量</span>: api/type/Vector3.md
        - <def>Box3Quaternion</def> / <def>GameQuaternion</def> <span block>四元数</span>: api/type/Quaternion.md
        - <def>Box3Bounds3</def> / <def>GameBounds3</def> <span block>三维区域空间</span>: api/type/Bounds3.md
        - <def>Box3RGBColor</def> / <def>GameRGBColor</def> <span block>RGB颜色</span>: api/type/RGBColor.md
        - <def>Box3RGBAColor</def> / <def>GameRGBAColor</def> <span block>RGBA颜色</span>: api/type/RGBAColor.md
      - <icon name='enum'>枚举</icon>:
        - <def>Box3BodyPart</def> / <def>GameBodyPart</def> <span block>身体部件类型</span>: api/type/enum/BodyPart.md
        - <def>Box3ButtonType</def> / <def>GameButtonType</def> <span block>按键类型</span>: api/type/enum/ButtonType.md
        - <def>Box3CameraMode</def> / <def>GameCameraMode</def> <span block>摄像机模式</span>: api/type/enum/CameraMode.md
        - <def>Box3InputDirection</def> / <def>GameInputDirection</def> <span block>输入方向</span>: api/type/enum/InputDirection.md
        - <def>Box3CameraFreezedAxis</def> / <def>GameCameraFreezedAxis</def>: api/type/enum/CameraFreezedAxis.md
        - <def>Box3PlayerMoveState</def> / <def>GamePlayerMoveState</def> <span block>玩家移动状态</span>: api/type/enum/PlayerMoveState.md
        - <def>Box3PlayerWalkState</def> / <def>GamePlayerWalkState</def> <span block>玩家步行状态</span>: api/type/enum/PlayerWalkState.md
        - <def>Box3DialogType</def> / <def>GameDialogType</def> <span block>对话框类型</span>: api/type/enum/DialogType.md
        - <def>SocialType</def> <span block>社交类型</span>: api/type/enum/SocialType.md
        - <def>Box3AnimationPlaybackState</def> / <def>GameAnimationPlaybackState</def> <span block>动画播放状态</span>: api/type/enum/AnimationPlaybackState.md
        - <def>Box3AnimationDirection</def> / <def>GameAnimationDirection</def> <span block>动画播放方向</span>: api/type/enum/AnimationDirection.md
        - <def>Box3Easing</def> / <def>GameEasing</def> <span block>动画缓动效果</span>: api/type/enum/Easing.md
      - <def>Box3PlayerEntity</def> / <def>GamePlayerEntity</def> <span block>玩家实体</span>: api/type/PlayerEntity.md
      - <def>Box3DialogCall</def> / <def>GameDialogCall</def> <span block>对话框调用</span>: api/class/Player.md/#Box3DialogCall
      - <def>Box3DialogParams</def> / <def>GameDialogParams</def> <span block>对话框配置</span>: api/type/DialogParams.md
      - <def>Box3DialogSelectResponse</def> / <def>GameDialogSelectResponse</def> <span block>选择对话框结果</span>: api/type/DialogSelectResponse.md
      - <def>Box3DialogCancelOption</def> / <def>GameDialogCancelOption</def> <span block>对话框取消选项</span>: api/type/DialogCancelOption.md
      - <def>Box3EventChannel</def> / <def>GameEventChannel</def> <span block>事件频道</span>: api/type/EventChannel.md
      - <def>Box3EventFuture</def> / <def>GameEventFuture</def>: api/type/EventFuture.md
      - <def>Box3EntityConfig</def> / <def>GameEntityConfig</def> <span block>实体配置</span>: api/type/EntityConfig.md
      - <def>Box3ZoneConfig</def> / <def>GameZoneConfig</def>: api/type/ZoneConfig.md
      - <def>Box3SelectorString</def> / <def>GameSelectorString</def>: api/type/SelectorString.md
      - <def>Box3RaycastOptions</def> / <def>GameRaycastOptions</def> <span block>射线检测配置</span>: api/type/RaycastOptions.md
      - <def>Box3RaycastResult</def> / <def>GameRaycastResult</def> <span block>射线检测结果</span>: api/type/RaycastResult.md
      - <def>Box3SoundEffect</def> / <def>GameSoundEffect</def>: api/type/SoundEffect.md
      - <def>Box3WorldKeyframe</def> / <def>GameWorldKeyframe</def>: api/type/WorldKeyframe.md
      - <def>Box3EntityKeyframe</def> / <def>GameEntityKeyframe</def>: api/type/EntityKeyframe.md
      - <def>Box3PlayerKeyframe</def> / <def>GamePlayerKeyframe</def>: api/type/PlayerKeyframe.md
      - <def>Box3AnimationPlaybackConfig</def> / <def>GameAnimationPlaybackConfig</def>: api/type/AnimationPlaybackConfig.md
      - <def>ListPageOptions</def> <span block>列表翻页配置</span>: api/type/ListPageOptions.md
      - <def>ReturnValue</def> <span block>数据查询返回</span>: api/type/ReturnValue.md
      - <def>JSONValue</def> <span block>类JSON格式</span>: api/type/JSONValue.md
      - <def>Box3HttpFetchParams</def> <span block>HTTP请求参数</span>: api/type/HttpFetchParams.md
      - <def>GameHttpFetchRequestOptions</def> <span block>HTTP请求配置</span>: api/type/HttpFetchRequestOptions.md
      - <def>GameHttpFetchHeaders</def> <span block>HTTP请求头配置</span>: api/type/HttpFetchHeaders.md
      - <def>Box3HttpHandler</def> / <def>GameHttpHandler</def> <span block>HTTP事件监听器</span>: api/type/HttpHandler.md
  - Client API参考:
    - api_client/index.md
  - 第三方模块参考:
    - modules/index.md
# - Getting started:
#   - Installation: getting-started.md
#   - Creating your site: creating-your-site.md
#   - Publishing your site: publishing-your-site.md
#   - Customization: customization.md
#   - Browser support: browser-support.md
#   - Philosophy: philosophy.md
#   - Alternatives: alternatives.md
#   - License: license.md
#   - Changelog:
#     - changelog/index.md
#     - How to upgrade: upgrade.md
# - Setup:
#   - Changing the colors: setup/changing-the-colors.md
#   - Changing the fonts: setup/changing-the-fonts.md
#   - Changing the language: setup/changing-the-language.md
#   - Changing the logo and icons: setup/changing-the-logo-and-icons.md
#   - Ensuring data privacy: setup/ensuring-data-privacy.md
#   - Setting up navigation: setup/setting-up-navigation.md
#   - Setting up site search: setup/setting-up-site-search.md
#   - Setting up site analytics: setup/setting-up-site-analytics.md
#   - Setting up social cards: setup/setting-up-social-cards.md
#   - Setting up tags: setup/setting-up-tags.md
#   - Setting up versioning: setup/setting-up-versioning.md
#   - Setting up the header: setup/setting-up-the-header.md
#   - Setting up the footer: setup/setting-up-the-footer.md
#   - Adding a git repository: setup/adding-a-git-repository.md
#   - Adding a comment system: setup/adding-a-comment-system.md
#   - Building for offline usage: setup/building-for-offline-usage.md
#   - Extensions:
#     - setup/extensions/index.md
#     - Python Markdown: setup/extensions/python-markdown.md
#     - Python Markdown Extensions: setup/extensions/python-markdown-extensions.md
# - Reference:
#   - reference/index.md
#   - Admonitions: reference/admonitions.md
#   - Annotations: reference/annotations.md
#   - Buttons: reference/buttons.md
#   - Code blocks: reference/code-blocks.md
#   - Content tabs: reference/content-tabs.md
#   - Data tables: reference/data-tables.md
#   - Diagrams: reference/diagrams.md
#   - Footnotes: reference/footnotes.md
#   - Formatting: reference/formatting.md
#   - Grids: reference/grids.md
#   - Icons, Emojis: reference/icons-emojis.md
#   - Images: reference/images.md
#   - Lists: reference/lists.md
#   - MathJax: reference/mathjax.md
#   - Tooltips: reference/tooltips.md
# - Insiders:
#   - insiders/index.md
#   - Getting started:
#     - Installation: insiders/getting-started.md
#     - Changelog: insiders/changelog.md
# - Blog:
#   - blog/index.md
#   - 2022:
#     - blog/2022/chinese-search-support.md
#   - 2021:
#     - blog/2021/the-past-present-and-future.md
#     - blog/2021/excluding-content-from-search.md
#     - blog/2021/search-better-faster-smaller.md
