site_name: Box3 社区文档
repo_url: https://github.com/qndm/box3-docs
edit_uri: edit/main/docs/
repo_name: box3-docs
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.tabs
    - navigation.expand
    - content.tabs.link
    - search.suggest
    - search.highlight
  language: zh
  palette:
    # primary: blue
    # accent: indigo
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: 亮色模式
    - scheme: slate
      primary: blue
      toggle:
        icon: material/weather-night
        name: 暗色模式
  custom_dir: overrides
extra_css:
  - _assets/icons.css
  - _assets/global.css

extra_javascript:
  - _assets/iconsParser.js
  - _assets/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/gsap/3.11.3/gsap.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/gsap/3.11.3/ScrollToPlugin.min.js
  - _assets/anchorParser.js
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/icons
  - pymdownx.tilde
  - tables
plugins:
  - search:
      lang: en
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      width: "100%"
      height: auto
      zoomable: true
      draggable: true
      auto_caption: false
      caption_position: bottom
  - minify:
      minify_html: true
nav:
  - 主页:
      - 介绍:
          - 欢迎: index.md
          - 关于文档: about.md
          - 更新: changes.md
          - 计划: todo.md
  - 学习:
      - learn/index.md
      - 粒子特效:
          - learn/particle/index.md
      - JavaScript:
          - learn/js/index.md
          - 基础教程:
              - learn/js/base/index.md
              - 开始: learn/js/base/index.md
              - Hello, World!: learn/js/base/01-hello-world.md
              - 欢迎玩家: learn/js/base/02-greeting.md
      - 大佬の宝典:
          - SQL快速入门: learn/community-articles/Nomen-sql.md
          - OOP（面向对象编程）快速入门: learn/community-articles/Nomen-oop.md
          - 如何优雅地写注释: learn/community-articles/Nomen-comment.md
          - 快速上手函数: learn/community-articles/Nomen-function.md
      - 算法:
          - BFS: learn/arithmetic/BFS.md
          - DFS: learn/arithmetic/DFS.md
  - 实例教程:
      - example/index.md
      - LightDotCutter 简单PVE游戏:
          - 起步: example/light-dot-cutter/01-start.md
          - 生成敌人: example/light-dot-cutter/02-setup-enemy.md
      #     - 实现玩家攻击: example/light-dot-cutter/03-attack.md
      #     - 添加敌人和玩家的血量: example/light-dot-cutter/04-health.md
      #     - 设置奖励: example/light-dot-cutter/05-reward.md
      #     - 添加特效: example/light-dot-cutter/06-effect.md
      #     - 重构和扩展: example/light-dot-cutter/07-extra.md
      #     - 优化: example/light-dot-cutter/08-optimization.md
  - API参考:
      - api/index.md
      - <icon name='namespace'>图标参考</icon>: api/icons.md
      - <def>world</def> & <def>Box3World</def> / <def>GameWorld</def>: api/world.md
      - <def>voxels</def> & <def>Box3Voxels</def> / <def>GameVoxels</def>: api/voxels.md
      - <def>Box3Entity</def> / <def>GameEntity</def>: api/entity.md
      - <def>Box3Player</def> / <def>GamePlayer</def>: api/player.md
      - <def>db</def> & <def>Box3DataBase</def>: api/database.md
      - <def>storage</def> & <def>GameStorage</def> & <def>GameDataStorage</def>: api/storage.md
      - <icon name='event'>事件</icon>:
          - <def>Box3TickEvent</def>: api/event/TickEvent.md
          - <def>Box3RespawnEvent</def>: api/event/RespawnEvent.md
          - <def>Box3DamageEvent</def>: api/event/DamageEvent.md
          - <def>Box3DieEvent</def>: api/event/DieEvent.md
          - <def>Box3EntityEvent</def>: api/event/EntityEvent.md
          - <def>Box3PlayerEntityEvent</def> / <def>GamePlayerEntityEvent</def>: api/event/PlayerEntityEvent.md
          - <def>Box3ChatEvent</def>: api/event/ChatEvent.md
          - <def>Box3ClickEvent</def>: api/event/ClickEvent.md
          - <def>Box3InputEvent</def>: api/event/InputEvent.md
          - <def>Box3EntityContactEvent</def>: api/event/EntityContactEvent.md
          - <def>Box3VoxelContactEvent</def>: api/event/VoxelContactEvent.md
          - <def>Box3FluidContactEvent</def>: api/event/FluidContactEvent.md
          - <def>Box3InteractEvent</def>: api/event/InteractEvent.md

      - <icon name='type'>结构类型</icon>:
          - <icon name='namespace'>基本数据类型</icon>:
            - <def>string</def> & <def>String</def>: api/type/base/String.md
            - <def>number</def> & <def>Number</def>: api/type/base/Number.md
            - <def>boolean</def> & <def>Boolean</def>: api/type/base/Boolean.md
            - <def>Partial</def>: api/type/base/Partial.md
            - <def>URL</def>: api/type/base/URL.md
          - <icon name='namespace'>Box3 基本数据类型</icon>:
            - <def>Box3Vector3</def> / <def>GameVector3</def>: api/type/Vector3.md
            - <def>Box3Quaternion</def> / <def>GameQuaternion</def>: api/type/Quaternion.md
            - <def>Box3Bounds3</def> / <def>GameBounds3</def>: api/type/Bounds3.md
            - <def>Box3RGBColor</def> / <def>GameRGBColor</def>: api/type/RGBColor.md
            - <def>Box3RGBAColor</def> / <def>GameRGBAColor</def>: api/type/RGBAColor.md
          - <def>Box3EventChannel</def> / <def>GameEventChannel</def>: api/type/EventChannel.md
          - <def>Box3EventFuture</def> / <def>GameEventFuture</def>: api/type/EventFuture.md
          - <def>Box3EntityConfig</def> / <def>GameEntityConfig</def>: api/type/EntityConfig.md
          - <def>Box3SelectorString</def> / <def>GameSelectorString</def>: api/type/SelectorString.md
          - <def>Box3RaycastOptions</def> / <def>GameRaycastOptions</def>: api/type/RaycastOptions.md
          - <def>Box3RaycastResult</def> / <def>GameRaycastResult</def>: api/type/RaycastResult.md
          - <def>Box3SoundEffect</def> / <def>GameSoundEffect</def>: api/type/SoundEffect.md
          - <def>Box3ButtonType</def> / <def>GameButtonType</def>: api/type/ButtonType.md
          - <def>Box3Animation</def> / <def>GameAnimation</def>: api/type/Animation.md
          - <def>Box3WorldKeyframe</def> / <def>GameWorldKeyframe</def>: api/type/WorldKeyframe.md
          - <def>Box3EntityKeyframe</def> / <def>GameEntityKeyframe</def>: api/type/EntityKeyframe.md
          - <def>Box3PlayerKeyframe</def> / <def>GamePlayerKeyframe</def>: api/type/PlayerKeyframe.md
          - <def>Box3AnimationPlaybackConfig</def> / <def>GameAnimationPlaybackConfig</def>: api/type/AnimationPlaybackConfig.md
# - Getting started:
#   - Installation: getting-started.md
#   - Creating your site: creating-your-site.md
#   - Publishing your site: publishing-your-site.md
#   - Customization: customization.md
#   - Browser support: browser-support.md
#   - Philosophy: philosophy.md
#   - Alternatives: alternatives.md
#   - License: license.md
#   - Changelog:
#     - changelog/index.md
#     - How to upgrade: upgrade.md
# - Setup:
#   - Changing the colors: setup/changing-the-colors.md
#   - Changing the fonts: setup/changing-the-fonts.md
#   - Changing the language: setup/changing-the-language.md
#   - Changing the logo and icons: setup/changing-the-logo-and-icons.md
#   - Ensuring data privacy: setup/ensuring-data-privacy.md
#   - Setting up navigation: setup/setting-up-navigation.md
#   - Setting up site search: setup/setting-up-site-search.md
#   - Setting up site analytics: setup/setting-up-site-analytics.md
#   - Setting up social cards: setup/setting-up-social-cards.md
#   - Setting up tags: setup/setting-up-tags.md
#   - Setting up versioning: setup/setting-up-versioning.md
#   - Setting up the header: setup/setting-up-the-header.md
#   - Setting up the footer: setup/setting-up-the-footer.md
#   - Adding a git repository: setup/adding-a-git-repository.md
#   - Adding a comment system: setup/adding-a-comment-system.md
#   - Building for offline usage: setup/building-for-offline-usage.md
#   - Extensions:
#     - setup/extensions/index.md
#     - Python Markdown: setup/extensions/python-markdown.md
#     - Python Markdown Extensions: setup/extensions/python-markdown-extensions.md
# - Reference:
#   - reference/index.md
#   - Admonitions: reference/admonitions.md
#   - Annotations: reference/annotations.md
#   - Buttons: reference/buttons.md
#   - Code blocks: reference/code-blocks.md
#   - Content tabs: reference/content-tabs.md
#   - Data tables: reference/data-tables.md
#   - Diagrams: reference/diagrams.md
#   - Footnotes: reference/footnotes.md
#   - Formatting: reference/formatting.md
#   - Grids: reference/grids.md
#   - Icons, Emojis: reference/icons-emojis.md
#   - Images: reference/images.md
#   - Lists: reference/lists.md
#   - MathJax: reference/mathjax.md
#   - Tooltips: reference/tooltips.md
# - Insiders:
#   - insiders/index.md
#   - Getting started:
#     - Installation: insiders/getting-started.md
#     - Changelog: insiders/changelog.md
# - Blog:
#   - blog/index.md
#   - 2022:
#     - blog/2022/chinese-search-support.md
#   - 2021:
#     - blog/2021/the-past-present-and-future.md
#     - blog/2021/excluding-content-from-search.md
#     - blog/2021/search-better-faster-smaller.md
